### ISSUE TITLE
Nea smart 2.0

### ISSUE THREAD

**Issue by StefAmbe** [Jeoffreybauvin/pyrehau_neasmart#4]
Bonjour,
Merci pour votre travail.
Auriez-vous quelques pistes pour interagir avec un système Nea Smart 2.0?

**Comment by Jeoffreybauvin** [comment]
On parle bien de cette interface ?

![image](https://user-images.githubusercontent.com/701928/215321886-8ae4fddc-2213-4d4c-a16c-588e54d996f2.png)

Si oui, c'est bien ce que ce projet fait :).

**Comment by StefAmbe** [comment]
Hélas non, avec Nea Smart 2.0, tout semble passer par un cloud Rehau et le pilotage se fait via une application Androïd ou iOS.

**Comment by Jeoffreybauvin** [comment]
Ah :(. Ne possédant pas de Nea Smart 2.0, je ne vais pas pouvoir faire grand chose :/.

**Comment by StefAmbe** [comment]
Merci quand même.

Le mer. 1 févr. 2023, 18:37, Jeoffrey B. ***@***.***> a
écrit :
